[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd report-app && npm install"]

[phases.build]
cmds = ["cd report-app && npx prisma generate && npm run build"]

[start]
cmd = "cd report-app && npx prisma db push --accept-data-loss --skip-generate && (npx prisma db seed || true) && npm start"
